### ISSUE TITLE
hey everyone , i have one issue about image input 

### ISSUE THREAD

**Issue by manhdoan291** [deepc94/photo-id-ocr#2]
doan@doan-5547:~/Documents/photo-id-ocr$ python preprocess.py -i Image2.jpg 
Traceback (most recent call last):
  File "preprocess.py", line 35, in <module>
    (_, cnts, _) = cv2.findContours(thresh, cv2.RETR_EXTERNAL,
ValueError: not enough values to unpack (expected 3, got 2)
----------------------
#help me

**Comment by dalsi137** [comment]
i have the same issue...
File "preprocess.py", line 35, in
(_, cnts, _) = cv2.findContours(thresh, cv2.RETR_EXTERNAL,
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by manhdoan291** [comment]
Please update opencv to 3.8.3 or another version 3, uninstall your old
version
using pip 3 install opencv-python==3.8.3
