### ISSUE TITLE
hey , i have one issues

### ISSUE THREAD

**Issue by manhdoan291** [deepc94/photo-id-ocr#3]
~/Documents/photo-id-ocr$ python segment.py -i f_Image3.jpg
Traceback (most recent call last):
  File "segment.py", line 28, in <module>
    cv2.rectangle(mask, (0,0), (image.shape[1]/2,image.shape[0]), 255, -1)
TypeError: integer argument expected, got float
#help me

**Comment by deepc94** [comment]
you have to use floor division:
`image.shape[1]/2,` should be changed to either `image.shape[1]//2,` or `int(image.shape[1]/2),`

**Comment by manhdoan291** [comment]
Thanks ,
